
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: crowdly_development

test:
  <<: *default
  database: crowdly_test
  
production:
  <<: *default
  database: crowdly_production
  username: crowdly
  password: <%= ENV['CROWDLY_DATABASE_PASSWORD'] %>
